;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        org-beginning-of-line
        org-self-insert-command
        org-todo
        smex
        ))

(setq mc/cmds-to-run-once
      '(
        ))
