Style/AsciiComments:
  Description: 'Use only ascii symbols in comments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#english-comments'
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets
  SupportedStyles:
    - ruby19
    - hash_rockets
Metrics/LineLength:
  Max: 200
  AllowURI: true
  URISchemes:
    - http
    - https
Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 200

Style/IfUnlessModifier:
  MaxLineLength: 200
Style/WhileUntilModifier:
  MaxLineLength: 200

Style/CommentAnnotation:
  Keywords:
Metrics/MethodLength:
  CountComments: false
  Max: 20
Rails/ActionFilter:
  EnforcedStyle: action
  SupportedStyles:
    - action
    - filter
  Include:
    - app/controllers/**/*.rb
Rails/DefaultScope:
  Include:
    - app/models/**/*.rb
Rails/HasAndBelongsToMany:
  Include:
    - app/models/**/*.rb
Rails/Output:
  Include:
    - app/**/*.rb
    - config/**/*.rb
    - db/**/*.rb
    - lib/**/*.rb

Rails/ReadWriteAttribute:
  Include:
    - app/models/**/*.rb
Rails/ScopeArgs:
  Include:
    - app/models/**/*.rb
Rails/Validation:
  Include:
    - app/models/**/*.rb

Style/BlockComments:
  Description: 'Do not use block comments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-block-comments'
  Enabled: false
Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false
